# Site wide global vars - eg. {{ site.title }} can be used in templates
title: RDS Local
subtitle: RDS
version: 0.12.2
cssSize: 45KB
cssG: 10KB
jsSize: 10KB
jsG: 6KB
url: /docs/
#fw: Carleton
#cms: CU
fw: Elective
cms: Clear
cssPath: /docs/css/docs.css
homecssPath: /docs/css/hp.css
jsPath: /docs/js/docs.js
jsPathHome: /docs/js/hp.js

blocks:
    -
        name: Alert Header
        handle: alertheader
        section: header
        theme: core
    -
    -
        name: Banner
        handle: banner
        section: header
        theme: core
    -
        name: Global Nav
        handle: globalnav
        section: header
        theme: cms
    -
        name: Login
        handle: login
        section: header
        theme: core
    -
        name: Masthead
        handle: masthead
        section: header
        theme: core
    -
        name: Search
        handle: search
        section: header
        theme: core
    -
        name: Card Grid
        handle: cardgrid
        section: main
        theme: core
    -
        name: Content
        handle: content
        section: main
        theme: core
    -
        name: Listing
        handle: listing
        section: main
        theme: na
    -
        name: Text-Image
        handle: textimg
        section: main
        theme: fw
    -
        name: Footer Brand
        handle: footerbrand
        section: footer
        theme: core
    -
        name: Footer Simple (Missing end notes)
        handle: footersimple
        section: footer
        theme: na
    -
        name: Footer Sitemap
        handle: footersitemap
        section: footer
        theme: fw
    -
        name: Sidebar
        handle: sidebar
        section: aside
        theme: na

components:
    -
        name: Badge (No content)
        handle: badge
        section: alerts
        theme: core
    -
        name: Heading (No content)
        handle: heading
        section: headings
        theme: core
    -
        name: Call to Action
        handle: cta-button
        section: buttons
        theme: core
    -
        name: Social Media (Review required)
        handle: social-button
        section: buttons
        theme: core
    -
        name: Card
        handle: card
        section: cards
        theme: core
    -
        name: Accordion (Missing end notes)
        handle: accordion
        section: content
        theme: core
    -
        name: Image Caption
        handle: imagecaption
        section: content
        theme: core
    -
        name: Table (No content)
        handle: table
        section: content
        theme: core
    -
        name: Video (No content)
        handle: video
        section: content
        theme: core
    -
        name: Form (No content)
        handle: form
        section: forms
        theme: core
    -
        name: Search (No content)
        handle: search
        section: forms
        theme: core
    -
        name: Icon Library (Review required)
        handle: library
        section: icons
        theme: core
    -
        name: Carleton University Logo (No content)
        handle: carleton
        section: logos
        theme: core
    -
        name: Ravens Athletics Logo (No content)
        handle: ravens
        section: logos
        theme: core
    -
        name: Submenu (No content)
        handle: submenu
        section: nav
        theme: core

images: https://cu-raven.s3.amazonaws.com/assets/img/raven/

some_global_images:
    -
        filename: img1.jpg
        alt: /
    -
        filename: img2.jpg
        alt: /
    -
        filename: img3.jpg
        alt: /

sitemenu:
    -
        title: first item
        url: url
    -
        title: second item
        url: url

        submenu:
            -
                title: level 2 first
                url: url

                level3:
                    -
                        title: level 3 first
                        url: url
                    -
                        title: level 3 two
                        url: url

        submenu:
            -
                title: last item
                url: url
